[tool.poetry]
name = "py-slides-term"
version = "0.0.1"
description = "A python module for terminology extraction from presentation slides"
authors = ["Yuya Suwa"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.9"
mecab-python3 = "^1.0.3"
"pdfminer.six" = "^20201018"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
black = "^20.8b1"
pep8-naming = "^0.11.1"
flake8-quotes = "^3.2.0"
pre-commit = "^2.9.3"
pytest = "^6.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
