[tool.poetry]
name = "py-slides-term"
version = "0.2.0"
description = "A python module for terminology extraction from presentation slides"
authors = ["Yuya Suwa"]
license = "MIT License"
readme = "README.md"
homepage = "https://github.com/kumachan-mis/py-slides-term"
repository = "https://github.com/kumachan-mis/py-slides-term"
keywords = ["terminology extraction", "technical term", "pdf"]

[tool.poetry.dependencies]
python = ">=3.7"
mecab-python3 = "^1.0.3"
"pdfminer.six" = "^20201018"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
black = "^20.8b1"
pep8-naming = "^0.11.1"
flake8-quotes = "^3.2.0"
pre-commit = "^2.9.3"
pytest = "^6.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
